require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'

target 'example' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

  use_frameworks!
  use_native_modules!
end

target 'example-tvOS' do
  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
